// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Info returns the current state snapshot the frontend needs on load.
 */
export interface Info {
    "provider": string;
    "model": string;
    "work_dir": string;
    "onboarded": boolean;
    "name": string;
    "messages": MsgView[] | null;
    "sessions": SessionView[] | null;
}

/**
 * MsgView is a plain serializable view of a chat message for the frontend.
 */
export interface MsgView {
    /**
     * user | assistant | system
     */
    "role": string;
    "text": string;
}

/**
 * SessionView is a plain serializable summary of a saved session.
 */
export interface SessionView {
    "name": string;
    "provider": string;
    "model": string;
    "work_dir": string;
    "updated": string;
    "preview": string;
}
