// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails-bound AppService for GoDucky GUI. It wraps the shared
 * agent runtime (the same one the CLI uses) behind methods the frontend calls
 * directly, and pushes streaming output to the UI via application events.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AppVersion returns the GoDucky GUI version.
 */
export function AppVersion(): $CancellablePromise<string> {
    return $Call.ByID(2623354138);
}

/**
 * ApplySetup finishes the first-run wizard: mark onboarded, save config, init agent.
 */
export function ApplySetup(): $CancellablePromise<void> {
    return $Call.ByID(3245325862);
}

/**
 * Approve answers a pending tool-approval prompt.
 */
export function Approve(id: string, ok: boolean): $CancellablePromise<boolean> {
    return $Call.ByID(3637480072, id, ok);
}

/**
 * DeleteSession deletes a saved chat.
 */
export function DeleteSession(name: string): $CancellablePromise<void> {
    return $Call.ByID(2224689900, name);
}

/**
 * EnsureOllamaModel pulls a model through Ollama if it isn't local yet.
 */
export function EnsureOllamaModel(model: string): $CancellablePromise<void> {
    return $Call.ByID(3035669908, model);
}

/**
 * GetInfo fetches config + auth + sessions all at once.
 */
export function GetInfo(): $CancellablePromise<$models.Info | null> {
    return $Call.ByID(786082973);
}

/**
 * GetModels lists models for a provider (live where possible, else curated).
 */
export function GetModels(providerName: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(2861623075, providerName);
}

/**
 * HasAPIKey reports whether a key is available for the provider.
 */
export function HasAPIKey(providerName: string): $CancellablePromise<boolean> {
    return $Call.ByID(2972702794, providerName);
}

/**
 * HasModel checks whether the given Ollama model is already pulled.
 */
export function HasModel(model: string): $CancellablePromise<boolean> {
    return $Call.ByID(4042477486, model);
}

/**
 * InstallOllama downloads and installs Ollama for the current OS in the
 * background, streaming status updates as events.
 */
export function InstallOllama(): $CancellablePromise<void> {
    return $Call.ByID(4147237956);
}

/**
 * IsRunning reports whether an agent turn is in progress.
 */
export function IsRunning(): $CancellablePromise<boolean> {
    return $Call.ByID(1088908902);
}

/**
 * ListSessions returns the saved chats, newest first.
 */
export function ListSessions(): $CancellablePromise<$models.SessionView[] | null> {
    return $Call.ByID(2242685362);
}

/**
 * NewChat clears the current conversation, auto-saving it first if non-empty.
 */
export function NewChat(): $CancellablePromise<void> {
    return $Call.ByID(2559101165);
}

/**
 * OllamaStatus reports whether the Ollama server is installed and running.
 */
export function OllamaStatus(): $CancellablePromise<{ [_ in string]?: any } | null> {
    return $Call.ByID(103433111);
}

/**
 * OpenURL opens a URL in the system browser.
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(205485416, url);
}

/**
 * Providers lists the supported provider names.
 */
export function Providers(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3192635443);
}

/**
 * PullModel pulls (downloads) a model through Ollama in the background.
 */
export function PullModel(model: string): $CancellablePromise<void> {
    return $Call.ByID(2531580985, model);
}

/**
 * RecommendedLocalModels lists the curated local model shortlist.
 */
export function RecommendedLocalModels(): $CancellablePromise<string[] | null> {
    return $Call.ByID(2166096715);
}

/**
 * RemoveModel removes a locally pulled Ollama model.
 */
export function RemoveModel(model: string): $CancellablePromise<void> {
    return $Call.ByID(727906604, model);
}

/**
 * RenameSession renames a saved chat.
 */
export function RenameSession(oldName: string, newName: string): $CancellablePromise<void> {
    return $Call.ByID(4173449563, oldName, newName);
}

/**
 * Resume loads a saved chat into the working conversation.
 */
export function Resume(nameOrNum: string): $CancellablePromise<void> {
    return $Call.ByID(4247064600, nameOrNum);
}

/**
 * SaveAPIKey validates and saves an API key for a provider, then switches to it.
 */
export function SaveAPIKey(providerName: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(211076801, providerName, key);
}

/**
 * SaveSession saves (or overwrites) the current chat under the given name.
 */
export function SaveSession(name: string): $CancellablePromise<void> {
    return $Call.ByID(3404929106, name);
}

/**
 * Send starts a new agent turn with the given user prompt. It returns
 * immediately; streaming output is pushed to the frontend as events.
 */
export function Send(prompt: string): $CancellablePromise<void> {
    return $Call.ByID(3099078997, prompt);
}

/**
 * SetAutoApprove toggles auto-approval of file/command actions.
 */
export function SetAutoApprove(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(3746790163, on);
}

/**
 * SetConfigValue sets a dotted config key (like the CLI's /config).
 */
export function SetConfigValue(key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(2433214976, key, value);
}

/**
 * SetModel sets a model for the active provider.
 */
export function SetModel(name: string): $CancellablePromise<void> {
    return $Call.ByID(3162391254, name);
}

/**
 * SetWorkDir changes the working directory (creates it if needed).
 */
export function SetWorkDir(dir: string): $CancellablePromise<void> {
    return $Call.ByID(851204499, dir);
}

/**
 * StartLocalModelPulls starts pulling each of the given models through Ollama.
 */
export function StartLocalModelPulls(models: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2082327683, models);
}

/**
 * Stop cancels the in-flight agent turn.
 */
export function Stop(): $CancellablePromise<void> {
    return $Call.ByID(1991152683);
}

/**
 * SwitchProvider sets the active provider (does not require a key for ollama).
 */
export function SwitchProvider(name: string): $CancellablePromise<void> {
    return $Call.ByID(1644573570, name);
}
